apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
spec:
  data:
    {{- range $path, $_ :=  .Files.Glob  "../../migrations/**.sql" }}
    {{ $path | trimPrefix "../../migrations/" }}: |- 
  {{ $.Files.Get $path | indent 4 }}
    {{ end }}