apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  {{- range $path, $_ := .Files.Glob "migrations/**.sql" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}