apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.deployment.name }}
spec:
  stringData:
    DB_HOST: {{ .Values.secret.deployment.stringData.DB_HOST }}
    DB_SCHEMA: {{ .Values.secret.deployment.stringData.DB_SCHEMA }}
    DB_USER: {{ .Values.secret.deployment.stringData.DB_USER }}
    DB_PASSWORD: {{ .Values.secret.deployment.stringData.DB_PASSWORD | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.statefulSet.name }}
spec:
  stringData:
    MYSQL_ROOT_PASSWORD: {{ .Values.secret.statefulSet.stringData.MYSQL_ROOT_PASSWORD | quote }}
    MYSQL_DATABASE: {{ .Values.secret.statefulSet.stringData.MYSQL_DATABASE }}