services:
  migration:
    build: 
      dockerfile: docker/migrations/Dockerfile
      context: ..
    container_name: linkflow_migration
    environment:
      DB_HOST: "db"
      DB_SCHEMA: linkflow
      DB_USER: root
      DB_PASSWORD: 12345
    depends_on:
      db:
        condition: service_healthy
  api:
    build: 
      dockerfile: docker/app/Dockerfile
      context: ..
    container_name: linkflow
    ports:
      - "8080:8000"
    environment:
      DB_HOST: "db"
      DB_SCHEMA: linkflow
      DB_USER: root
      DB_PASSWORD: 12345
      PORT: 8000
      REDIS_HOST: cache:6379
    depends_on:
      migration:
        condition: service_completed_successfully
      cache:
        condition: service_started
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=linkflow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345"]
      interval: 5s
      timeout: 5s
      retries: 10
  cache:
    container_name: redis
    image: redis:7.4-alpine
    ports:
      - 6379:6379
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
