deployment:
  name: linkflow-app
  labels:
    app: linkflow
  replicas: 1
  image:
    name: iagouvea/linkflow
    version: latest
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

statefulSet:
  name: linkflow-db
  labels:
    app: mysql
  image:
    name: mysql
    version: 8.0

service:
  deployment:
    name: linkflow-app-svc
    type: NodePort
    port: 80

  statefulSet:
    name: linkflow-db-svc
    type: ClusterIP
    port: 3306

secret:
  deployment:
    name: linkflow-secrets
    stringData:
      DB_HOST: linkflow-db-svc
      DB_SCHEMA: linkflow
      DB_USER: root
      DB_PASSWORD: 12345
  statefulSet:
    name: mysql-secrets
    stringData:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: linkflow

configMap:
  name: migration-files