deployment:
  name: linkflow-app
  labels:
    app: linkflow
  replicas: 1
  image:
    name: iagouvea/linkflow
    version: latest
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  startupProbe:
    path: /
    failureThreshold: 10
    periodSeconds: 5   

statefulSet:
  db:
    name: linkflow-db
    labels:
      app: mysql
    image:
      name: mysql
      version: 8.0
    volumes:
      storage: 1Gi
  cache:
    name: linkflow-cache
    labels:
      app: redis
    image:
      name: redis
      version: 7.4-alpine

service:
  deployment:
    name: linkflow-app-svc
    type: NodePort
    port: 80

  statefulSet:
    db:
      name: linkflow-db-svc
      type: ClusterIP
      port: 3306
    cache:
      name: linkflow-cache-svc
      type: ClusterIP
      port: 6379

secret:
  deployment:
    name: linkflow-secrets
    stringData:
      DB_HOST: linkflow-db-svc
      DB_SCHEMA: linkflow
      DB_USER: root
      DB_PASSWORD: 12345
      REDIS_HOST: linkflow-cache-svc:6379
  statefulSet:
    name: mysql-secrets
    stringData:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: linkflow

configMap:
  name: migration-files